name: ci-cd-module-work-1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.1
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.1
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
      - name: Html tests report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report.html

